### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by rickyyx** [Teched-U/video-seg#1]
# API

### Key Frame Shots Segment Component (Vicky)
Take in a long video, outputs segmented shots. Sample output:

```yaml
{
    "features": {
        # Timestamps when each shot started
        "timestamps": [0.0, 1.0, 3, 4],

        # For each shot, also output a list of keyframes frame number (If possible)
        # It can be in different formats that is easy for you to generate:
        #  - These can be the raw frame image paths, e.g. 'xxx.png'
        #  - Eact timestamps of the frame in the video, e.g. '13.3'
        "frames": [
                [0],
                [40, 90, 100],
                [123, 300, 900],
                [1300, 1400],
        ],
    },
    # ABSOLUTE path to the video
    "video_name": "/tmp/data/easytopic/XXXXX.mp4"
}
```
